# Perfil mysql: DB_ENGINE=mysql. Crear antes la base:  CREATE DATABASE edumanager;
spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/edumanager}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
